### ISSUE TITLE
`invalid_key: end_row` error whenever running `Neogen`

### ISSUE THREAD

**Issue by cdkini** [danymat/neogen#82] opened 2022-03-14 17:12 UTC
Whenever I run `Neogen`, I hit the following error:

```
 E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:83: Vim(lua):E5108: Error executing lua ...are/nvim/site/pack/pac
ker/opt/neogen/lua/neogen/mark.lua:72: invalid key: end_row
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
```

I'm still able to generate the annotation after the error arises. I'm using Packer and setting up with:
```
    {
        'danymat/neogen',
        cmd = "Neogen",
        setup = function() mappings.neogen() end,
        config = function() require('neogen').setup() end
    },
```

Really love the work you've done here!

Version: [2.6.0](https://github.com/danymat/neogen/releases/tag/2.6.0)
OS: MacOS Monterey 12.2.1

**Comment by danymat** [comment] 2022-03-14 18:24
Hello !

> Really love the work you've done here!

Thanks, it means a lot to me !

By the way, which neovim version are you in ? We support `neovim 0.6+` only

**Comment by cdkini** [comment] 2022-03-14 18:29
Oops forgot to include that!

I'm running `NVIM v0.7.0-dev+2135-gd3585e0ec` (based on `nvim --version`)

**Comment by danymat** [comment] 2022-03-14 18:32
Hmm, I cannot reproduce the issue, are you sure it's not related to packer compile ? Can you try deleting `packer_compiled.lua` file, and re-run `:PackerCompile` ?

**Comment by danymat** [comment] 2022-03-14 18:34
If you still have the issue afterwards, can you provide me a simple function where Neogen fails, as well as your neogen mappings ?

**Comment by cdkini** [comment] 2022-03-14 21:29
I tried deleting `packer_compiled.lua` and re-compiling but no luck!

I'm trying some lazy-loading (inspired by NvChad) so that might be causing an issue. I originally only loaded Neogen after `:Neogen` was called but changing that didn't seem to do the trick.

Here's my installation file: https://github.com/cdkini/nvim/blob/lua/lua/plugins/init.lua#L242-L247
Here are my relevant mappings: https://github.com/cdkini/nvim/blob/lua/lua/core/mappings.lua#L107-L110

It seems like this is user error so I'll keep tinkering! Really appreciate the time you've spent here - worst case, I'll press `<Enter>` one time to get past the errors so I get to annotating 🙇🏽 

Feel free to close this down if the solution isn't obvious or immediately available.

**Comment by danymat** [comment] 2022-03-14 21:40
This is weird in fact, I will keep this issue open if someone has the same error. 
It seems like it's a packer issue, because if it was only Neogen error you shouldn't have Packer log there.

Maybe try unsetting lazy loading here, and recompile again.
One last thing, is the issue still here is you set `tag = "2.5.0"` ?

**Comment by cdkini** [comment] 2022-03-14 22:06
Hmm I tried to remove lazy loading but it hasn't helped. I just tried setting the tag a minor version back and that also didn't work.

For some additional context, I've tried this on both TypeScript and Python LSP's so I think we can rule that out. I'll keep digging!

**Comment by danymat** [comment] 2022-03-19 12:56
> mm I tried to remove lazy loading but it hasn't helped

Did you recompile after removing lazy loading ?

By the way, be sure to add `requires = "nvim-treesitter/nvim-treesitter"` in your neogen packer config

**Comment by hassec** [comment] 2022-03-22 10:16
FWIW, I see the same error: 
![image](https://user-images.githubusercontent.com/11351671/159458217-3c426ab5-f486-480b-8292-78466bdfa3d9.png)

super simple file:
```cpp
int tmp( int a ) { return a + 10; }
```
cursor on `tmp` and trigger neogen leads to the error above.

**Comment by hassec** [comment] 2022-03-22 10:28
Ok writing that I was using `0.6.0` actually surprised me and I double checke my other machine and that was running `0.6.1` and didn't  see this error. So I've just upgraded the `0.6.0` nvim that was seeing the error to `0.6.1` and now the error is gone :tada:    

I know that doesn't really help that much towards fixing it, but might be a good enough way to fix it for any `0.6.0` user reading this.

**Comment by danymat** [comment] 2022-03-23 13:11
This is really weird indeed. I'm afraid this issue is neovim related. Let's keep it open to see if other people report this behavior

**Comment by danymat** [comment] 2022-03-23 13:12
@cdkini Can you update to latest neovim version and see if you still have the error ?

**Comment by cdkini** [comment] 2022-03-23 13:31
Oops completely forgot about this sorry @danymat! I did try to recompile after lazy loading but it did not work.

I upgraded with Homebrew to this version just now: `NVIM v0.7.0-dev+2777-g52fe8eae0`.

That seems to have done the trick!

**Comment by danymat** [comment] 2022-03-23 13:42
Nice ! Closing this issue and will update readme to allow only 0.6.1+

**Closed** 2022-03-23 13:53 UTC
Labels: bug
