### ISSUE TITLE
Can't create documentation for a python class

### ISSUE THREAD

**Issue by SingularisArt** [danymat/neogen#107] opened 2022-09-13 21:41 UTC
When I run `:Neogen class` on a python class, I get the following error:

```
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:192: attempt to index local 'node' (a nil value) stack traceback:
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:192: in function 'get_node_text'
        ...ack/packer/start/neogen/lua/neogen/utilities/helpers.lua:32: in function 'get_node_text'
        ...packer/start/neogen/lua/neogen/configurations/python.lua:188: in function 'extract'
        .../site/pack/packer/start/neogen/lua/neogen/granulator.lua:34: in function 'granulator'
        ...m/site/pack/packer/start/neogen/lua/neogen/generator.lua:226: in function 'generate'
        [string ":lua"]:1: in main chunk
```

Here's my neogen configuration:

```lua
neogen.setup({
  enabled = true,
  languages = {
    python = {
      template = {
        annotation_convention = "google_docstrings",
      },
    },
  },
})
```

**Comment by danymat** [comment] 2022-09-19 22:00
Hello ! : https://github.com/danymat/neogen/issues/108#issuecomment-1251607617

Feels like the TS parser for python has been updated, i will look into it

**Comment by danymat** [comment] 2022-10-17 09:38
Hello, is it possible to provide me an example of class where this problem appears ?

**Comment by maximyurevich** [comment] 2022-10-23 23:51
Please fix this

**Comment by danymat** [comment] 2022-10-23 23:55
I would love to but I need more context : what's not working and a example of a snippet that for not work for you

**Comment by maximyurevich** [comment] 2022-10-24 00:48
https://imgur.com/Lje8xdj.png
everything is easy, there is no way to create docstring for python class

**Comment by SingularisArt** [comment] 2022-10-24 00:55
Yeah. I get the same error:

```
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:238: attempt to index local 'node' (a nil value)     
stack traceback:                                                                                                                     
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:238: in function 'get_node_text'                                        
        ...pack/plugins/opt/neogen/lua/neogen/utilities/helpers.lua:33: in function 'get_node_text'                                  
        .../plugins/opt/neogen/lua/neogen/configurations/python.lua:231: in function 'extract'                                       
        ...g/nvim/pack/plugins/opt/neogen/lua/neogen/granulator.lua:34: in function 'granulator'                                     
        ...ig/nvim/pack/plugins/opt/neogen/lua/neogen/generator.lua:226: in function 'generate'                                      
        [string ":lua"]:1: in main chunk                                                                                             
```

**Comment by danymat** [comment] 2022-10-24 08:59
Hello @maximyurevich, as i told twice before, i need more context than the error message to be able to reproduce it. If i ask this is because my local machine correctly generates the documentations, so there is something i cannot reproduce.

I need: 
- example of a class that does the error when trying to generate.
- Your neogen version (`:h neogen-changelog`)

Only after this i can be able to quickly address this issue

**Comment by maximyurevich** [comment] 2022-10-24 13:10
> Hello @maximyurevich, as i told twice before, i need more context than the error message to be able to reproduce it. If i ask this is because my local machine correctly generates the documentations, so there is something i cannot reproduce.
> 
> I need:
> 
> * example of a class that does the error when trying to generate.
> * Your neogen version (`:h neogen-changelog`)
> * Your neovim version
> 
> Only after this i can be able to quickly address this issue
> 
> PS: a simple class like this does generate a python doc on my end:
> 
> ```python
> class Test:
> 
>     """[TODO:description]
> 
>     :param a: [TODO:attribute]
>     :param c: [TODO:attribute]
>     """
>     def __init__(self, a):
>         self.a = a
>         self.c = c
> ```

My class doesn't use constructor

**Comment by SingularisArt** [comment] 2022-10-24 13:22
Here's an example class:

```python
class Lecture:
    def __init__(self, file_path: str) -> None:
        self.date = 0
        self.week = 0
        self.number = 0
        self.title = 0

    def edit(self) -> None:
        return

    def new(self) -> None:
        return
```

My current neovim version is: `NVIM v0.8.0`.

My current neogen version is: `2.10.1`.

**Comment by danymat** [comment] 2022-10-24 14:05
@SingularisArt thank you for your input, I'm checking it out after work

**Comment by SingularisArt** [comment] 2022-10-24 14:11
@danymat Take your time.

**Comment by danymat** [comment] 2022-10-25 08:20
Hello, I just tried to generate the documentation with `:Neogen class` and it works with google docstrings:

```python
class Lecture:
    """

    Attributes: 
        date: [TODO:attribute]
        week: [TODO:attribute]
        number: [TODO:attribute]
        title: [TODO:attribute]
    """
    def __init__(self, file_path: str) -> None:
        self.date = 0
        self.week = 0
        self.number = 0
        self.title = 0

    def edit(self) -> None:
        return

    def new(self) -> None:
        return
```

Can you try to uninstall python parser and install it again ? I don't have a clue of what is not working on your end.
Maybe can you try providing a screen of the result of `:TSP` of the code sample you provided.

**Comment by bryant-the-coder** [comment] 2022-10-25 11:58
works for me also @danymat

**Comment by SingularisArt** [comment] 2022-10-25 19:51
@danymat I updated the tree-sitter for python, but I still get the same error, even when using `google_docstrings`.
When I run `:TSP`, I just get `E492: Not an editor command: TSP`. Am I missing a dependency or something?

**Comment by SingularisArt** [comment] 2022-10-27 21:18
@danymat Alright. I think I found the bug. When I run `Neogen class` on the following class:

```python
class Lecture:
    def __init__(self, file_path):
        self.file_path = file_path

        lecture_match = ""
```

I get the error from above.
**BUT** when I run the same command on the following class:

```python
class Lecture:
    def __init__(self, file_path):
        self.file_path = file_path

        self.lecture_match = ""
```

It works! Here's the output:

```python
class Lecture:
    """

    Attributes: 
        file_path: 
        lecture_match: 
    """
    def __init__(self, file_path):
        self.file_path = file_path

        self.lecture_match = ""
```

So, it appears that neogen runs into issues when the class has variables that aren't class variables, like `self.lecture_match`. It also runs into the same issue with functions within the class. For example, when I run the same command on the following class:

```python
class Lecture:
    def __init__(self, file_path):
        self.file_path = file_path

        self.lecture_match = ""

    def edit(self):
        listen_location = "/tmp/nvim.pipe"
        args = []
```

I get the same error.
**BUT**, when I run the same command on the following class:

```python
class Lecture:
    def __init__(self, file_path):
        self.file_path = file_path

        self.lecture_match = ""

    def edit(self):
        self.listen_location = "/tmp/nvim.pipe"
        self.args = []
```

It works. Here's the output:

```python
class Lecture:
    """

    Attributes: 
        file_path: 
        lecture_match: 
        listen_location: 
        args: 
    """
    def __init__(self, file_path):
        self.file_path = file_path

        self.lecture_match = ""

    def edit(self):
        self.listen_location = "/tmp/nvim.pipe"
        self.args = []
```

**Comment by maximyurevich** [comment] 2022-10-27 22:21
After deleting all my non-class variables from methods neogen start working

**Comment by maximyurevich** [comment] 2022-10-31 22:43
Neogen start working for classes after installing https://github.com/nvim-treesitter/nvim-tree-docs

**Comment by maximyurevich** [comment] 2022-11-02 19:21
temporary solution to use https://github.com/heavenshell/vim-pydocstring

**Comment by danymat** [comment] 2022-11-02 23:09
Hello, sorry for the delay, i had to take care of different things but haven't forgotten you
I tried to fix the bug, thanks a lot @SingularisArt for pointing out the bug, i was able to reproduce and find the root cause very quickly. Summary?: poor coding practices that were written at the beginning of neogen, which is not checking out nil values in fetching treesitter nodes data.

I hope it's now fixing, I keep this issue open while waiting for your feedback.
Thank you all.

**Comment by SingularisArt** [comment] 2022-11-03 00:44
@danymat It works for me now! Do you think you'd be able to add the methods within the class as well?

**Comment by danymat** [comment] 2022-11-03 18:39
@SingularisArt what do you mean ? Can you provide an example ?

**Comment by SingularisArt** [comment] 2022-11-03 20:53
Say we have the following class:

```python
class SomeClass:
    def __init__(self, a, b, c, x, y, z):
        self.a = a
        self.b = b
        self.c = c
        self.x = x
        self.y = y
        self.z = z

    def some_function(self):
        pass

    def another_some_function(self):
        pass

    def final_some_function(self):
        pass
```

and when you run `Neogen class`, you get

```python
class SomeClass:
    """

    Attributes: 
        a: 
        b: 
        c: 
        x: 
        y: 
        z: 

    Methods:
        some_function: 
        another_some_function: 
        final_some_function: 
    """

    def __init__(self, a, b, c, x, y, z):
        self.a = a
        self.b = b
        self.c = c
        self.x = x
        self.y = y
        self.z = z

    def some_function(self):
        pass

    def another_some_function(self):
        pass

    def final_some_function(self):
        pass
```

**Comment by maximyurevich** [comment] 2022-11-03 21:01
> Say we have the following class:
> 
> ```python
> class SomeClass:
>     def __init__(self, a, b, c, x, y, z):
>         self.a = a
>         self.b = b
>         self.c = c
>         self.x = x
>         self.y = y
>         self.z = z
> 
>     def some_function(self):
>         pass
> 
>     def another_some_function(self):
>         pass
> 
>     def final_some_function(self):
>         pass
> ```
> 
> and when you run `Neogen class`, you get
> 
> ```python
> class SomeClass:
>     """
> 
>     Attributes: 
>         a: 
>         b: 
>         c: 
>         x: 
>         y: 
>         z: 
> 
>     Methods:
>         some_function: 
>         another_some_function: 
>         final_some_function: 
>     """
> 
>     def __init__(self, a, b, c, x, y, z):
>         self.a = a
>         self.b = b
>         self.c = c
>         self.x = x
>         self.y = y
>         self.z = z
> 
>     def some_function(self):
>         pass
> 
>     def another_some_function(self):
>         pass
> 
>     def final_some_function(self):
>         pass
> ```

I think its overengineering, I never seen a class docstrings describing methods

**Comment by danymat** [comment] 2022-11-21 09:24
Hello, sorry for the late update.
Do you have by any means a reference to docstrings that describe this behavior ? Because, if it's on the spec, it should be indeed added eventually

**Comment by danymat** [comment] 2022-12-28 10:48
Hello, any updates ? 
If not, I will close this issue as it seems resolved. 
Best regards

**Comment by SingularisArt** [comment] 2022-12-28 11:09
@danymat Sorry for the late replay (school and stuff). I don't have any reference to any docstrings that do this, but I'll try and find some. If not, by the end of tomorrow, I'll just close this issue if nothing else arises.

**Comment by danymat** [comment] 2022-12-28 11:15
@SingularisArt Thank you for your feedback, and no worries !

**Comment by danymat** [comment] 2023-01-03 12:35
Hello ! Closing this issue as it seems to be resolved.
Feel free to reopen if the need arises !
Cheers

**Closed by danymat** 2023-01-03 12:35 UTC
Labels: bug, under review
